server:
  port: 8080
spring:
  datasource:
    ## Postgres
    url: jdbc:postgresql://${DATABASE_HOST:localhost}:5432/task-management
    username: postgres
    password: postgres
    ## default connection pool
    hikari:
      connectionTimeout: 20000
      maximumPoolSize: 5
      poolName: SpringBootJPAHikariCP
      maxLifetime: 2000000
    continue-on-error: true

api:
  security:
    token:
      secret: ${JWT_SECRET:my-secret-key}