server:
  port: 8080
spring:
  datasource:
    ## Postgres
    url: jdbc:postgresql://${DATABASE_HOST:localhost}:5432/task-management
    username: postgres
    password: postgres
    ## default connection pool
    hikari:
      connectionTimeout: 20000
      maximumPoolSize: 5
      poolName: SpringBootJPAHikariCP
      maxLifetime: 2000000
    continue-on-error: true

  #Config service send email
  mail:
    host: smtp.gmail.com
    port: 587
    username: matheusjosejuliao@gmail.com
    password: meiebmvadcjkjrbu
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
          ssl.trust: smtp.gmail.com

api:
  security:
    token:
      secret: ${JWT_SECRET:my-secret-key}